# Generated by Django 5.1 on 2025-05-03 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='join_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='membership',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'handler'}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='society_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
