# Generated by Django 5.1 on 2025-05-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_join_code_customuser_membership_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='membership',
            new_name='memberships',
        ),
    ]
