# Generated by Django 5.1 on 2025-05-03 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_handler_viewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='memberships',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('executive', 'Executive'), ('deputy_director', 'Deputy Director'), ('director', 'Director'), ('vice_president', 'Vice President'), ('president', 'President'), ('other', 'Other')], default='other', max_length=20)),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_memberships', to='users.handler')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_memberships', to='users.viewer')),
            ],
            options={
                'unique_together': {('viewer', 'handler')},
            },
        ),
    ]
